version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: beart-db
    environment:
      POSTGRES_USER: prod
      POSTGRES_PASSWORD: CHANGE_ME
      POSTGRES_DB: beart-panel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: